// Per-storefront color bridge. The AI Builder gives every brand its own
// `colors.{primary, secondary, accent}` triplet; we expose those plus two
// derived tokens as CSS custom properties so storefront components can use
// `var(--brand-primary)` instead of inline-styling every button. The shape
// (radius, padding, type) stays on the Forge token grid — only color
// swaps per brand.

export type BrandColors = {
  primary: string;
  secondary: string;
  accent?: string;
};

// Relative luminance (sRGB) per WCAG 2.x. We use it once to decide whether
// a CTA on top of `--brand-primary` should be white or near-black.
function luminance(hex: string): number {
  const m = hex.replace('#', '').match(/.{2}/g);
  if (!m || m.length < 3) return 0;
  const [r, g, b] = m.map(s => parseInt(s, 16) / 255) as [number, number, number];
  const lin = (c: number) =>
    c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
}

// 92% lightness version of the primary, generated by mixing primary with
// white in HSL space. Used for soft section backgrounds.
function softVariant(hex: string): string {
  const m = hex.replace('#', '').match(/.{2}/g);
  if (!m || m.length < 3) return '#f5f5f5';
  const [r, g, b] = m.map(s => parseInt(s, 16) / 255);
  // Mix 88% white into the source colour — a fast approximation of "L=92%".
  const mix = (c: number) => Math.round((c * 0.12 + 0.88) * 255);
  return `#${[mix(r!), mix(g!), mix(b!)]
    .map(n => n.toString(16).padStart(2, '0'))
    .join('')}`;
}

// Returns the CSS string the page needs to inline. Calling code drops it
// inside a <style> tag at the top of the storefront — server-rendered, so
// no flash. Scoped under `[data-brand="<slug>"]` to avoid leaking into
// other UI on the same page (the admin preview frame, for example).
export function brandTokenCss(slug: string, colors: BrandColors): string {
  const primary = colors.primary;
  const secondary = colors.secondary;
  const accent = colors.accent ?? '#fafafa';
  const ctaFg = luminance(primary) > 0.6 ? 'var(--fg)' : '#ffffff';
  const soft = softVariant(primary);
  return `
[data-brand="${slug}"] {
  --brand-primary: ${primary};
  --brand-secondary: ${secondary};
  --brand-accent: ${accent};
  --brand-primary-soft: ${soft};
  --brand-cta-fg: ${ctaFg};
}
`.trim();
}

// Free-shipping threshold (cents). Picked from the industry-typical $75
// boutique-DTC anchor. Surfaced here so the cart's progress bar and the
// announcement bar agree.
export const FREE_SHIPPING_THRESHOLD_CENTS = 7500;
