#!/usr/bin/env node
/**
 * build-tokens.mjs
 *
 * Reads design/design.lock.json (the design source of truth) and writes
 * apps/web/src/styles/tokens.css. The lock drives the live theme: when the
 * design tool ships a new lock, re-run this script and the implementation
 * theme follows.
 *
 * Run:
 *   node scripts/build-tokens.mjs
 *   pnpm tokens   (alias from root package.json)
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const LOCK_PATH = resolve(ROOT, 'design/design.lock.json');
const OUT_PATH = resolve(ROOT, 'apps/web/src/styles/tokens.css');

const lock = JSON.parse(readFileSync(LOCK_PATH, 'utf8'));
const { tokens } = lock;

const lightVars = renderColorBlock(tokens.color.light);
const darkVars = renderColorBlock(tokens.color.dark);
const radiusVars = renderRadiusBlock(tokens.radius);
const shadowVars = renderShadowBlock(tokens.shadow);
const fontVars = renderFontBlock(tokens.typography);
const spacingComment = renderSpacingComment(tokens.spacing);

const out = `/* AUTOGENERATED FROM design/design.lock.json
 * Do not edit by hand. Regenerate with: pnpm tokens
 * Design version: ${lock.version} · tokens version: ${tokens.version}
 * Generated at: ${new Date().toISOString()}
 */

:root {
  /* ---------- color (light theme — default) ---------- */
${lightVars}

  /* ---------- typography ---------- */
${fontVars}

  /* ---------- radius ---------- */
${radiusVars}

  /* ---------- shadow ---------- */
${shadowVars}
${spacingComment}}

[data-theme="dark"] {
${darkVars}
}
`;

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, out);
const rel = OUT_PATH.replace(`${ROOT}/`, '');
console.log(`tokens: wrote ${rel} (design v${lock.version}, tokens v${tokens.version})`);

// ---------- helpers ----------

function renderColorBlock(palette) {
  return Object.entries(palette)
    .map(([key, value]) => `  --${key}: ${value};`)
    .join('\n');
}

function renderRadiusBlock(radius) {
  // The design exposes --radius (default) and --radius-lg in styles.css.
  // The lock also declares "sm", which we expose for completeness.
  const lines = [];
  if (radius.sm) lines.push(`  --radius-sm: ${radius.sm};`);
  if (radius.default) lines.push(`  --radius: ${radius.default};`);
  if (radius.lg) lines.push(`  --radius-lg: ${radius.lg};`);
  return lines.join('\n');
}

function renderShadowBlock(shadow) {
  const lines = [];
  if (shadow.sm) lines.push(`  --shadow-sm: ${shadow.sm};`);
  if (shadow.default) lines.push(`  --shadow: ${shadow.default};`);
  if (shadow.lg) lines.push(`  --shadow-lg: ${shadow.lg};`);
  return lines.join('\n');
}

function renderFontBlock(typography) {
  return [
    `  --font: ${typography.font};`,
    `  --font-mono: ${typography['font-mono']};`,
    `  --font-serif: ${typography['font-serif']};`,
  ].join('\n');
}

function renderSpacingComment(spacing) {
  // Spacing is consumed via Tailwind theme; document the scale here so the lock
  // is self-explanatory in the generated file.
  if (!spacing) return '';
  return `\n  /* spacing scale (consumed by Tailwind theme): ${spacing.scale.join(', ')} (base ${spacing.base}px) */\n`;
}
